'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,selected='maya',inputMode='chat',panel='chat',renderer=null,toastTimer,detailStamp=0,lastTasks='',lastChat='',lastActivity='',connected=false;
const formatTime=t=>`${String(Math.floor(t/3600)%24).padStart(2,'0')}:${String(Math.floor(t/60)%60).padStart(2,'0')}`;
const dialogueCache=new Map();
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
async function command(data){if(window.townReplay)throw Error('Return to the live town to give commands.');const payload={id:crypto.randomUUID(),...data};let response;for(let n=0;n<2;n++){try{response=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});break;}catch(error){if(n)throw Error('Cannot reach the simulation server.');}}const result=await response.json();if(!response.ok)throw Error(result.error||'Command failed');return result;}
function action(data){return command(data).then(r=>{if(r.message)toast(r.message);return r;}).catch(e=>{toast(e.message);return null;});}
function setInput(mode){inputMode=mode;$('#input-mode-help').textContent=mode==='task'?'This creates a tracked request after Alex reaches the resident.':'Chat sends a message. To start an errand, select Assign task.';document.querySelectorAll('[data-input]').forEach(b=>b.classList.toggle('active',b.dataset.input===mode));const name=state?.agents.find(a=>a.id===selected)?.name||'Maya';$('#send').innerHTML=(mode==='task'?'Ask ':'Say it to ')+esc(name)+' <span>↗</span>';$('#message').placeholder=mode==='task'?'Bring a coffee to Noah, please.':`Hi ${name}, what are you doing today?`;}
function select(id){selected=id;if(renderer)renderer.selected=id;lastChat='';detailStamp=0;if(state)render();setInput(inputMode);loadDetail();}
function setPanel(name){panel=name;for(const p of ['chat','memory','plan'])$('#panel-'+p).hidden=p!==name;document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));loadDetail();}
async function loadDetail(){if(!state||window.townReplay)return;const id=selected;try{const response=await fetch('/api/agents/'+id);if(!response.ok)return;const detail=await response.json();if(id!==selected||window.townReplay)return;dialogueCache.set(id,detail.dialogue||[]);$('#memories').innerHTML=detail.memories.length?detail.memories.map(m=>`<div class="memory ${detail.retrieved.includes(m.id)?'retrieved':''}"><div class="kind">${esc(m.kind)} · ${esc(m.confidence||'')} · ${formatTime(m.created)}</div><p>${esc(m.text)}</p><small>Memory #${m.id} · importance ${m.importance}/10${m.evidence.length?' · evidence '+esc(JSON.stringify(m.evidence)):''}</small></div>`).join(''):'<p class="empty">New experiences will appear here.</p>';$('#plans').innerHTML=(detail.current_action?`<div class="plan"><strong>Now: ${esc(detail.current_action.activity)}</strong><p>${esc(detail.current_action.place)}</p></div>`:'')+detail.plan.map((p,i)=>`<div class="plan"><strong>${i+1}. ${esc(p.activity)}</strong><p>At the ${esc(p.place)}</p></div>`).join('');$('#relationships').innerHTML=Object.entries(detail.relationships).map(([aid,score])=>`<div class="relationship">${esc(state.agents.find(a=>a.id===aid)?.name||aid)} <span class="small">· familiarity ${score}/100</span></div>`).join('')||'<p class="empty">Relationships grow through conversations.</p>';}catch{}}
function render(){const a=state.agents.find(a=>a.id===selected);if(!a)return;$('#time').textContent=formatTime(state.time);$('#time').title='Simulated time · six game seconds per real second at 1×';$('#mode').textContent=state.model.mode==='demo'?'OFFLINE DEMO':state.model.last_error?'MODEL FALLBACK':state.model.mode==='ollama'?'OLLAMA LIVE':'LIVE MODEL';$('#mode-note').textContent=state.model.mode==='demo'?'Demo conversations and decisions use rules.':(state.model.mode==='ollama'?'Local Ollama · ':'Generated dialogue and decisions · ')+state.model.model;$('#usage').textContent=state.model.mode==='demo'?'Every world update is saved atomically':`${state.model.requests}/${state.model.request_limit} requests · ${state.model.tokens.toLocaleString()} tokens`;$('#model-help-text').textContent=state.model.last_error?state.model.last_error+' Safe demo fallbacks are in use.':state.model.mode==='demo'?'Offline mode uses rules and a small set of supported requests. No model requests are made.':'Live mode generates dialogue, activity choices, task interpretation, and reflections. World rules still validate every action.';$('#pause').textContent=state.paused?'Resume':'Pause';$('#speed').value=String(state.speed);$('#cafe-open').checked=state.cafe_open;$('#resident-name').textContent=a.name;$('#resident-role').textContent=a.role;$('#resident-status').textContent=a.thinking?'Thinking…':a.status;
  document.querySelectorAll('#residents button').forEach(b=>b.classList.toggle('active',b.dataset.id===selected));$('#needs').innerHTML=Object.entries(a.needs).map(([key,value])=>{const v=Math.round(value);return `<div><div class="need-label"><span>${esc(key)}</span><span>${v}</span></div><div class="need-track"><div class="need-fill" style="width:${v}%"></div></div></div>`;}).join('');$('#inventory').textContent=a.inventory.length?'Carrying: '+a.inventory.map(i=>i.kind).join(', '):'Hands free';
  const p=state.pending_interaction;$('#interaction-status').textContent=p?`${state.paused?'Resume the town to continue. ':''}Alex is walking over to ${state.agents.find(a=>a.id===p.agent)?.name||'the resident'}…`:a.thinking?'Waiting for a reply…':'';
  const recentDialogue=state.events.filter(e=>e.kind==='dialogue'&&(e.actor===selected||(e.payload.recipients||[]).includes(selected)));
  const dialogues=[...new Map([...(window.townReplay?[]:(dialogueCache.get(selected)||[])),...recentDialogue].map(e=>[e.id,e])).values()].sort((a,b)=>b.id-a.id).slice(0,40).reverse(),chatKey=JSON.stringify(dialogues.map(e=>e.id))+selected;
  if(chatKey!==lastChat){lastChat=chatKey;const log=$('#chat-log'),atBottom=log.scrollHeight-log.scrollTop-log.clientHeight<40;log.innerHTML=dialogues.length?dialogues.map(e=>`<div class="chat-line ${e.actor==='visitor'?'player':''}"><div class="speaker">${esc(state.agents.find(a=>a.id===e.actor)?.name||e.actor)} · ${formatTime(e.time)}</div><p>${esc(e.text.slice(e.text.indexOf(':')+1).trim())}</p></div>`).join(''):'<p class="empty">Say hello. Alex will walk over before speaking.</p>';if(atBottom)log.scrollTop=log.scrollHeight;}
  const tasks=[...state.tasks].reverse(),taskKey=JSON.stringify(tasks);if(taskKey!==lastTasks){lastTasks=taskKey;const active=tasks.filter(t=>!['completed','cancelled','failed','declined'].includes(t.status)).length;$('#task-count').textContent=active?`${active} active request${active===1?'':'s'}`:'No active requests';$('#tasks').innerHTML=tasks.length?tasks.slice(0,8).map(t=>`<article class="task"><div class="task-top"><span>${esc(state.agents.find(a=>a.id===t.agent)?.name||t.agent)}</span><span class="task-status ${esc(t.status)}">${esc(t.status)}</span></div><h3>${esc(t.request)}</h3>${t.plan?.length>1?`<small>Plan step ${t.plan_index+1}/${t.plan.length} · earlier steps verified: ${t.step_results.length}</small>`:''}<div class="steps">${t.steps.map((_,i)=>`<span class="step ${i<t.step?'done':''}"></span>`).join('')}</div><small>${esc(t.blocker||(t.status==='cancelled'?'Cancelled. This request will not continue.':t.status==='completed'?'Verified by world events.':t.steps[t.step]||'Request ended.'))}</small>${!['completed','cancelled','failed','declined'].includes(t.status)?`<button data-priority="${esc(t.id)}" data-paused="${t.status==='paused'}">${t.status==='paused'?'Resume':'Pause task'}</button> <button data-cancel="${esc(t.id)}">Cancel request</button>`:''}</article>`).join(''):'<p class="empty">Select a resident and assign a task. Its progress will appear here.</p>';}
  const events=state.events.filter(e=>e.kind!=='dialogue').slice(0,8),activityKey=JSON.stringify(events.map(e=>e.id));if(activityKey!==lastActivity){lastActivity=activityKey;$('#activity').innerHTML=events.map(e=>`<div class="event"><time>${formatTime(e.time)}</time><span>${esc(e.text)}</span></div>`).join('');}
  if(Date.now()-detailStamp>2000){detailStamp=Date.now();loadDetail();}
}
$('#message-form').addEventListener('submit',async e=>{e.preventDefault();const text=$('#message').value.trim();if(!text)return;$('#send').disabled=true;try{const result=await command({kind:inputMode,agent:selected,text});$('#message').value='';if(result.message)toast(result.message);}catch(error){toast(error.message);}finally{$('#send').disabled=false;}});
$('#message').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){$('#message-form').requestSubmit();e.preventDefault();}});
document.querySelectorAll('[data-input]').forEach(b=>b.onclick=()=>setInput(b.dataset.input));document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>setPanel(b.dataset.panel));document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{setInput('task');$('#message').value=b.dataset.example;$('#message').focus();});
$('#tasks').onclick=e=>{const priority=e.target.closest('[data-priority]');if(priority)action({kind:priority.dataset.paused==='true'?'resume_task':'suspend_task',task:priority.dataset.priority});const b=e.target.closest('[data-cancel]');if(b)action({kind:'cancel',task:b.dataset.cancel});};$('#pause').onclick=()=>state&&action({kind:'pause',paused:!state.paused});$('#speed').onchange=e=>action({kind:'speed',speed:Number(e.target.value)});$('#cafe-open').onchange=e=>action({kind:'cafe',open:e.target.checked});$('#save').onclick=()=>action({kind:'save'});$('#recenter').onclick=()=>renderer?.fit();$('#bubbles').onchange=e=>{if(renderer)renderer.bubbles=e.target.checked;};
async function start(){try{const response=await fetch('/api/layout');if(!response.ok)throw Error('Could not load the neighborhood');const layout=await response.json();for(const p of layout.residents.filter(a=>a.id!=='visitor')){const b=document.createElement('button');b.dataset.id=p.id;b.textContent=p.name;b.onclick=()=>select(p.id);$('#residents').append(b);}renderer=new SmallworldRenderer($('#world'),$('#portrait'),layout,window.ASSET_MANIFEST,select,(x,y)=>{if(renderer.room()!==(state.agents.find(a=>a.id==='visitor')?.room||'')){toast('Walk Alex into this room first.');return;}action({kind:'move',x,y});});await renderer.load();const source=new EventSource('/api/stream');source.onopen=()=>{connected=true;$('#connection').hidden=true;};source.onmessage=e=>{try{const incoming=JSON.parse(e.data);window.liveTownState=incoming;if(!window.townReplay){state=incoming;renderer.setState(state);render();window.updateTownTools?.();}}catch(error){toast('An update could not be displayed.');}};source.onerror=()=>{connected=false;$('#connection').textContent='Reconnecting to the local simulation…';$('#connection').hidden=false;};window.addEventListener('pagehide',()=>source.close());}catch(error){$('#connection').textContent=error.message;}}
start();
